---
abstract: 'Lightweight validator supporting Language Independent Validation Rules Specification (LIVR)'
author:
  - 'Viktor Turskyi <koorchik@cpan.org>'
build_requires:
  JSON: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.131490'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Validator-LIVR
no_index:
  directory:
    - t
    - inc
requires:
  Email::Valid: 0
  perl: 5.01
version: 0.02
